version: '2'
services:
    finacial_market-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/finacial_market/mongodb/:/data/db/
